### ISSUE TITLE
Build Components

### ISSUE THREAD

**Issue by jdlehne** [ivangreene/crushnote#11]
component to make:

Card Container
Card view (with card info)
Cheatsheet Card (with card summary/class count)
Card in play/out of play?
Private card alert

**Comment by jdlehne** [comment]
<img width="445" alt="chrome_2017-11-16_12-15-25" src="https://user-images.githubusercontent.com/28584727/32908170-64175ca6-cac8-11e7-8b18-af735e48ebfb.png">

<img width="225" alt="atom_2017-11-16_12-14-55" src="https://user-images.githubusercontent.com/28584727/32908168-62af4b08-cac8-11e7-81c1-22c79282fcee.png">
Made a quick cheat card json/component to plug into played hud
<img width="427" alt="atom_2017-11-16_12-13-06" src="https://user-images.githubusercontent.com/28584727/32908165-5f97ccb0-cac8-11e7-8f4e-c2f87d17b458.png">

**Comment by ivangreene** [comment]
I like the cheat sheet. That's another thing we were talking about, should the descriptions be on the cards or not?

**Comment by jdlehne** [comment]
Reworked components/minimized css for reworking
![image](https://user-images.githubusercontent.com/28584727/32987880-e699f7e2-ccbc-11e7-8d2a-9e563154ce4b.png)
<img width="960" alt="2017-11-18_23-56-02" src="https://user-images.githubusercontent.com/28584727/32987883-ee5d193c-ccbc-11e7-8caa-186f56d349dc.png">

**Comment by jdlehne** [comment]
So I'm making a main landing page 'lobby' after login, using purecss to keep the grid clean and uniform,
here is a first pass at some info that could be displayed/generated.
![image](https://user-images.githubusercontent.com/28584727/33043941-ab54a604-ce0c-11e7-9c22-e4d4b0809799.png)
Thoughts, comments, concerns?

**Comment by jdlehne** [comment]
![image](https://user-images.githubusercontent.com/28584727/33082033-688b59b8-cea1-11e7-99af-d5f16f08ae0c.png)

Made a seperate discard pile that could loop through what cards played/ or not played yet, if we wanted  to keep that information displayed?

**Comment by jdlehne** [comment]
![image](https://user-images.githubusercontent.com/28584727/33090462-ac565efa-ceb9-11e7-81bc-80dbdd8c3cfc.png)
Cleaned this up for legbility
