### ISSUE TITLE
Add socket.io to React app

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#19]
It's available to use for the front-end in React as the `socket.io-client` package.

**Comment by Jufrench** [comment]
Are we using socket.io for the chat feature or for dynamic updates of cards being played?

**Comment by ivangreene** [comment]
@Jufrench dynamic updates of the cards being played. And probably also chat when we get to that.
I describe some of the actions that might occur here: https://github.com/ivangreene/crushnote/wiki/socket.io-events

**Comment by buzzingnat** [comment]
An update on progress on socket.io implementation:
- I made user creation and authorization that uses socket.io
- @jdlehne made a basic user chat implementation using socket.io
