### ISSUE TITLE
Implement Auth using express-session

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#28]
`express-session` is set up and ready to handle authorizing users.
Due to limitations of socketio, we can only instantiate a session within an express route and not within a socketio event handler.
I think we should accept the username/password in a route, and then if the authentication is successful, assign a userid in `req.session.userid` or something like that, so that we will have it available in `socket.request.session`. Maybe we should define what authorization details should look like in a new Wiki page.

**Comment by buzzingnat** [comment]
I think we should use `bcrypt` for hashing and salting passwords before we store anything in our database. It looks like we will want to store sessions in mongodb rather than local RAM, so we can use the `connect-mongo` module for that.

**Comment by ivangreene** [comment]
Yeah it's already set up with `connect-mongo` and everything. I merged my latest into master so new branches can be based on that.

**Comment by buzzingnat** [comment]
Update on where this is so far:
### Sign Up
New user creation.
- **Done.**

### Log In
User authorization and session start.
Finished so far:
- Front end: form built, initial socket event named, data accessible.
- Back end: password comparison done.
Still to do:
- Front end: write socket.emit and socket.on functions
- Back end: write logic for accessing database, sending client side data to database for authorization, and sending database data forward to client. Create socket.on and socket.emit functions. add session logic. make sure to use express-session correctly to place the cookie on login.

**Comment by buzzingnat** [comment]
I think this is resolved for now. If we have further things we want to clean up about user auth, we can reopen this issue.
