### ISSUE TITLE
Clean up + reorganize server-side codebase

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#30]
We need to do some reorganization of the structure of server-side code, find some better naming conventions, and decide what should be a controller and what should be an abstraction of the ORM.

I think it will be easiest if one person takes this task on, and we do it at a time when we can collate different branches from a good working point, and put this into `master` so people can base future branches on this new structure.

I'm willing to take this on today and tomorrow, and please leave any suggestions in the comments here.

I'd like everyone to submit pull requests of their latest work sometime today so I can merge everything we have and then work from that base.

**Comment by ivangreene** [comment]
My ideas so far:
- ### `engine/`
  - Better naming conventions
  - Move into `lib/`
- ### `controllers/`
  - Better naming conventions
  - Merge the `*dbCalls` files in `lib/`, as these should really be the controllers. As of now, the `controllers/` are basically only routes. Thoughts?
- ### `lib/`
  - Merge `engine/` here.
  - Better organization conventions.
- ### `server.js`
  - Organize code and add more comments.
  - Move socket chat features into `routes/`.
- ### `routes/`
  - Create directory for socket calls.

Please comment with your thoughts!

**Comment by buzzingnat** [comment]
We currently have three sets of files that span the routes and controllers logic. I'm trying to think of a better way to name and organize them.

One thought I have is that we could organize it as *controllers* which contain the mongoose logic, *routes* which wrap the mongoose logic in an express-friendly way, and *api paths* which are the express calls with specific paths.

**Comment by ivangreene** [comment]
Right that's what I'm thinking too.
We could even just narrow that down further by combining _routes_ and _api paths_ since they will never be used independently of each other.

In my opinion, our _controllers_ should expose some basic CRUD operations, and also contain more app-specific operations. There's no point in abstracting from the methods that Mongoose exposes if we aren't making more specific methods for our own application.

**Comment by buzzingnat** [comment]
We could merge the **routes** logic and the **api paths** logic, but we'll end up with much longer files. I can pull my custom logic back from `usersController.js` into `userDbCalls.sj`, which will leave the current `controllers` files simple enough to merge into the files currently in `routes/api`. Then we would just have `controllers` and `routes` files. The problem is that I really like how simple and clean the current `routes` files look, and making this change would make them complicated and harder to read. The benefit would be a simpler directory structure, so it is probably worth it.

**Comment by ivangreene** [comment]
Beginning cleanup now in a clean directory.
Making sure we have coherent+comprehensive `package.json`s so that we can portably deploy the project. Making sure all env vars are covered in the Wiki.
Getting started on restructuring after that.
