### ISSUE TITLE
Decide on UI/CSS framework

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#5]
A decision needs to be made on the front end visual framework to be used. Good candidates should either be purely CSS, or be component based and integrate well with React.
A few possibilities:
Material Design - https://material.io/ - or possibly the React component based Material UI http://www.material-ui.com/#/
Bulma - https://bulma.io/
Pure.css - https://purecss.io/

**Comment by Jufrench** [comment]
**Material Design**
- I'm open to it, but it seems like it can get pretty heavy. If we kept the styling simple, I think we could make it work

**Bulma**
- Pretty simple to use but we wouldn't be challenging ourselves too much.

**Pure.css**
- From the quick peek I took, I kinda like it so far.

**Comment by ivangreene** [comment]
I think using pieces of Pure.css, especially the grid system, and then writing further custom styles could be an interesting approach.
Since we aren't going to be depending upon a huge amount of traditional elements and our game interface will need to be customized anyway, choosing individual components from an existing framework and building what we need would probably be the way to go.

**Comment by buzzingnat** [comment]
Pure.css looks nice to me from a few minutes of skimming the docs.

**Comment by Jufrench** [comment]
Well, then I guess Pure.css it is!

**Comment by ivangreene** [comment]
I dig!
It turns out Pure.css is written in plain CSS and doesn't have source available in Sass or Less.
Fortunately we can use SCSS, which is a superset of CSS (meaning that any valid CSS is already valid SCSS).
Pure.css is available as the npm package `purecss` and can be imported module-by-module something like this:
```
@import 'purecss/forms';
@import 'purecss/grids';
@import 'purecss/tables';
```

**Comment by ivangreene** [comment]
I'll close this for now because I think we've settled on https://github.com/yahoo/pure
This issue can be reopened if we want to change to a different one later

**Comment by ivangreene** [comment]
I think Material Icons would help us make a great interface - https://material.io/icons/
If anyone has any other icon sets they think would be good you should link them here!
