### ISSUE TITLE
Game View: Buttons

### ISSUE THREAD

**Issue by buzzingnat** [ivangreene/crushnote#69]
Remove Start Game, Join Game.
Move others and make them pretty.

**Comment by buzzingnat** [comment]
Buttons needed during game play:
- Play Card (display on selected card.)
- Show Cards (cheat sheet and guard selection)
- Show Discarded Cards
- Abandon Game

**Comment by jdlehne** [comment]
just pushed these, put the abandon game button back as well, still need to work out logic to handle pushing/parsing which cards have been played
