### ISSUE TITLE
When appropriate, show a player information about another player (e.g. Priest)

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#79]

**Comment by ivangreene** [comment]
TODO: show the player's card in PlayerMount. will be `props.player.hand`

**Comment by jdlehne** [comment]
For the sake of time saving, you want to take this one?  I spent some time banging my head against it and am unsure where to start.  You threw me some peanuts in getting on the right track, however I think you probably know the quick solution, I could spend the time fixing some other issues?
