### ISSUE TITLE
Sketch out REST API guidelines and formats

### ISSUE THREAD

**Issue by ivangreene** [ivangreene/crushnote#8]
Write a Wiki page roughly drafting the API routes needed

**Comment by buzzingnat** [comment]
Do we want to use something like this as a template, leaving blanks for everything we don't know?
https://gist.github.com/iros/3426278

Cons: it's a lot of information and takes up a lot of space. Pros: It looks like a really useful set of questions to answer for every call and a nicely laid out way to read them.

Another option might be something with less markdown so it's more condensed, maybe like:
```title: Get User
url: api/user/:id
method: get
params:
	- id, req: string
success: 
	- code: 200
	- content: {name: "jane", _id: "123abc", gameState: {}}
error:
	- code: 401
	- content: "user id not found"```

**Comment by ivangreene** [comment]
I like the second way being more condensed and easy to read as a code block. Maybe we could just add a descriptive comment in there also.

**Comment by ivangreene** [comment]
I'm gonna close this and open a new issue related to it, because we are moving more in the direction of things mostly being Socketio based. I think it should still consist of Wiki pages to document how the front-end will interact with the back-end.
